language: java
env:
- ES_VERSION=6.3.1 ES_DOWNLOAD_URL=https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-${ES_VERSION}.tar.gz
install:
- sudo ./install_fossa.sh
- wget ${ES_DOWNLOAD_URL}
- tar -xzf elasticsearch-${ES_VERSION}.tar.gz
- sudo ./elasticsearch-${ES_VERSION}/bin/elasticsearch-plugin install https://github.com/medcl/elasticsearch-analysis-ik/releases/download/v${ES_VERSION}/elasticsearch-analysis-ik-${ES_VERSION}.zip
- ./elasticsearch-${ES_VERSION}/bin/elasticsearch &
before_script:
- sed -i "s/compile\sproject/\/\/compile\ project/g" `grep "compile\sproject" -rl .`
- fossa
- sed -i "s/\/\/compile\sproject/compile\ project/g" `grep "\/\/compile\sproject" -rl .`
script:
- wget -q --waitretry=2 --retry-connrefused -T 10 -O - http://127.0.0.1:9200
- wget -q --waitretry=2 --retry-connrefused -T 10 -O - http://127.0.0.1:9200
- ./gradlew clean build jacocoFullReport
- ./gradlew jacocoMerge sonarqube -Dsonar.organization=librazy-github -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN
after_success:
- fossa test
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - $HOME/elasticsearch-${ES_VERSION}.tar.gz
  - $HOME/elasticsearch-${ES_VERSION}.tar.gz
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
addons:
  sonarcloud:
    organization: "librazy-github"
    token: $SONAR_TOKEN