language: java
install:
- sudo ./install_fossa.sh
before_script:
- sed -i "s/compile\sproject/\/\/compile\ project/g" `grep "compile\sproject" -rl .`
- fossa
- sed -i "s/\/\/compile\sproject/compile\ project/g" `grep "\/\/compile\sproject" -rl .`
addons:
  sonarcloud:
    organization: "librazy-github"
    token: $SONAR_TOKEN
script:
- ./gradlew clean build jacocoFullReport
- ./gradlew jacocoMerge sonarqube -Dsonar.organization=librazy-github -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN
after_success:
- fossa test
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
